[package]
name = "rust_physics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num="0.4.3"
ndarray="0.16.1"
libm="0.2.8"
